### ISSUE TITLE
Previously hidden titlebars re-appear after applying layout

### ISSUE THREAD

**Issue by hanschen** [TyberiusPrime/i3-instant-layout#3]
I hide the i3 titlebars with

    new_window 1pixel

After applying a layout with i3-instant-layout, the titlebars appear again.

**Comment by TyberiusPrime** [comment]
new_window is deprecated - does your issue still appear if you use the new default_border commands? 
See 
https://i3wm.org/docs/userguide.html#_default_border_style_for_new_windows

**Comment by hanschen** [comment]
Yes, it also happens with

    default_border pixel 1

By the way I use i3-gaps (installed from Arch Linux package), forgot to mention that.

    $ i3 --version
    i3 version 4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors

**Comment by TyberiusPrime** [comment]
Ok, so it's happening because of the window mapping/unmapping.

Now I could store the border setting before hand - but to reapply it, I'd have to focus each window in turn, wait-for-it-to-be-focused and reapply the border, because the i3 scripting api is really limited :(.

One last low effort attempt:
Can you try sticking a 
```for_window [class="^.*"] border pixel 1```
in your config?

**Comment by hanschen** [comment]
Adding

    for_window [class="^.*"] border pixel 1

works! The "real" solution sounds quite bothersome so I'm satisfied with this solution - you can close this Issue if you want. Maybe add a mention of it somewhere in the README for others with the same issue.
